package common

var (
	REQ_APP_AUTH                 = "REQ_APP_AUTH"
	REQ_ACCOUNT_AUTH             = "REQ_ACCOUNT_AUTH"
	REQ_ACCOUNT_HISTORICAL_DEALS = "REQ_ACCOUNT_HISTORICAL_DEALS"
	REQ_REFRESH_TOKEN            = "REQ_REFRESH_TOKEN"
	REQ_TRADER_INFO              = "REQ_TRADER_INFO"
	REQ_TREND_BARS               = "REQ_TREND_BARS"
	REQ_CLIENT_FAILURE           = "CH_CLIENT_AUTH_FAILURE"
	REQ_SYMBOL_LIST              = "REQ_SYMBOL_LIST"
)
