package common

var (
	REQ_APP_AUTH                 = "REQ_APP_AUTH"
	REQ_ACCOUNT_AUTH             = "REQ_ACCOUNT_AUTH"
	REQ_ACCOUNT_HISTORICAL_DEALS = "REQ_ACCOUNT_HISTORICAL_DEALS"
	REQ_REFRESH_TOKEN            = "REQ_REFRESH_TOKEN"
)
